FASTWeb/Models/FixAsset/FixAssetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace FASTWeb.Models.FixAsset
{
    public class FixAssetViewModel
    {
        [Display(Name="Fix Asset ID")]
        public int FixAssetID { get; set; }

        [Required(ErrorMessage="This field is required.")]
        [Display(Name="Model")]
        public string Model { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Serial Number")]
        public string SerialNumber { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Asset Tag")]
        public string AssetTag { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Brand")]
        public string Brand { get; set; }

        [Display(Name = "Remarks")]
        public string Remarks { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Acquisition Date")]
        [DataType(DataType.Date)]
        public DateTime? AcquisitionDate { get; set; }

        [Display(Name = "Expiry Date")]
        [DataType(DataType.Date)]
        public DateTime? ExpiryDate { get; set; }

        [Display(Name = "Issuer ID")]
        public int? IssuerID { get; set; }

        [Display(Name = "Issuer")]
        public string Issuer { get; set; }

        [Display(Name = "Location ID")]
        public int? LocationID { get; set; }

        [Display(Name = "Location")]
        public string Location { get; set; }

        [Display(Name = "Asset Type ID")]
        public int AssetTypeID { get; set; }

        [Display(Name = "Asset Type")]
        public string AssetType { get; set; }

        [Display(Name = "Asset Status ID")]
        public int AssetStatusID { get; set; }

        [Display(Name = "Asset Status")]
        public string AssetStatus { get; set; }

        [Display(Name = "Asset Class")]
        public int AssetClassID { get; set; }

        [Display(Name = "Asset Class")]
        public string AssetClass { get; set; }
    }
}

FASTWeb/Controllers/FixAssetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FASTWeb.Models.FixAsset;
using FASTService.Model;
using FASTService.Process;
using FASTService;
namespace FASTWeb.Controllers
{
    public class FixAssetController : Controller
    {
        //
        // GET: /FixAsset/
        [Authorize]
        public ActionResult Index()
        {
            FixAssetManagementProcess fixAssetManagement = new FixAssetManagementProcess();
            var AssetList = fixAssetManagement.GetAllAssets().Select(k => new FixAssetViewModel
            {
                FixAssetID = k.FixAssetID,
                Model = k.Model,
                SerialNumber = k.SerialNumber,
                AssetTag = k.AssetTag,
                Brand = k.Brand,
                Remarks = k.Remarks,
                AcquisitionDate = k.AcquisitionDate,
                ExpiryDate = k.ExpiryDate,

                Issuer = k.Issuer,

                Location = k.Location,

                AssetType = k.AssetType,

                AssetStatus = k.AssetStatus,

                AssetClass = k.AssetClass
            });
            return View(AssetList);
        }

        [Authorize]
        public ActionResult NewAsset()
        {
            FixAssetManagementProcess assetManagement = new FixAssetManagementProcess();
            LocationProcess location = new LocationProcess();
            IssuerProcess issuer = new IssuerProcess();

            ViewBag.Location = location.GetLocations();
            ViewBag.Issuer = issuer.GetIssuers();
            ViewBag.AssetType = assetManagement.GetAssetTypes();
            ViewBag.AssetStatus = assetManagement.GetAssetStatus();
            ViewBag.AssetClass = assetManagement.GetAssetClasses();
            return View(new FixAssetViewModel());
        }

        [HttpPost]
        [Authorize]
        public ActionResult SaveNewAsset(FixAssetViewModel assetModel)
        {
            FixAssetModel asset = new FixAssetModel();
            asset.Model = assetModel.Model;
            asset.SerialNumber = assetModel.SerialNumber;
            asset.AssetTag = assetModel.AssetTag;
            asset.Brand = assetModel.Brand;
            asset.Remarks = assetModel.Remarks;
            if (assetModel.AcquisitionDate != null)
                asset.AcquisitionDate = assetModel.AcquisitionDate;
            if (assetModel.ExpiryDate != null)
                asset.ExpiryDate = assetModel.ExpiryDate;
            if (assetModel.IssuerID != null)
                asset.IssuerID = assetModel.IssuerID;
            if (assetModel.LocationID != null)
                asset.LocationID = assetModel.LocationID;
            asset.AssetTypeID = assetModel.AssetTypeID;
            asset.AssetStatusID = 2;
            asset.AssetClassID = assetModel.AssetClassID;
            FixAssetManagementProcess assetManagement = new FixAssetManagementProcess();
            bool success = assetManagement.NewAsset(asset);

            return RedirectToAction("Index");
        }
        

        [Authorize]
        public ActionResult EditAsset(int mod)
        {
            int FixAssetID = mod;
            FixAssetManagementProcess assetManagement = new FixAssetManagementProcess();
            LocationProcess location = new LocationProcess();
            IssuerProcess issuer = new IssuerProcess();

           
            var AssetDetails = assetManagement.GetAllAssets().Where(k=>k.FixAssetID == FixAssetID).Select(k => new FixAssetViewModel
            {
                FixAssetID = k.FixAssetID,
                Model = k.Model,
                SerialNumber = k.SerialNumber,
                AssetTag = k.AssetTag,
                Brand = k.Brand,
                Remarks = k.Remarks,
                AcquisitionDate = k.AcquisitionDate,
                ExpiryDate = k.ExpiryDate,
                Issuer = k.Issuer,
                IssuerID = k.IssuerID,
                Location = k.Location,
                LocationID = k.LocationID,
                AssetType = k.AssetType,
                AssetTypeID = k.AssetTypeID,
                AssetStatus = k.AssetStatus,
                AssetStatusID = k.AssetStatusID,
                AssetClass = k.AssetClass,
                AssetClassID = k.AssetClassID
            }).FirstOrDefault();

            ViewBag.Location = location.GetLocations();
            ViewBag.Issuer = issuer.GetIssuers();
            ViewBag.AssetType = assetManagement.GetAssetTypes();
            ViewBag.AssetStatus = assetManagement.GetAssetStatus();
            ViewBag.AssetClass = assetManagement.GetAssetClasses();
            return View(AssetDetails);
        }
        
        [Authorize]
        [HttpPost]
        public ActionResult EditAsset(FixAssetViewModel assetModel)
        {
            FixAssetModel asset = new FixAssetModel();
            asset.FixAssetID = assetModel.FixAssetID;
            asset.Model = assetModel.Model;
            asset.SerialNumber = assetModel.SerialNumber;
            asset.AssetTag = assetModel.AssetTag;
            asset.Brand = assetModel.Brand;
            asset.Remarks = assetModel.Remarks;
            if(assetModel.AcquisitionDate != null)
                asset.AcquisitionDate = assetModel.AcquisitionDate;
            if (assetModel.ExpiryDate != null)
                asset.ExpiryDate = assetModel.ExpiryDate;
            if (assetModel.IssuerID != null)
                asset.IssuerID = assetModel.IssuerID;
            if (assetModel.LocationID != null)
                asset.LocationID = assetModel.LocationID;
            asset.AssetTypeID = assetModel.AssetTypeID;
            asset.AssetStatusID = assetModel.AssetStatusID;
            asset.AssetClassID = assetModel.AssetClassID;
            FixAssetManagementProcess assetManagement = new FixAssetManagementProcess();
            bool success = assetManagement.UpdateAsset(asset);
            return RedirectToAction("Index");
        }
	}
}

FASTWeb/Views/FixAsset/EditAsset.cshtml
@model FASTWeb.Models.FixAsset.FixAssetViewModel

@{
    ViewBag.Title = "NewAsset";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Asset</h2>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.FixAssetID)
        <div class="form-group">
            @Html.LabelFor(model => model.SerialNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SerialNumber, new { @class="form-control" })
                @Html.ValidationMessageFor(model => model.SerialNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssetTag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AssetTag, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssetTag)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Model, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Model)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Brand, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Brand)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AcquisitionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AcquisitionDate, new { @class = "form-control", @id = "adate" })
                @Html.ValidationMessageFor(model => model.AcquisitionDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ExpiryDate, new { @class = "form-control", @id = "edate" })
                @Html.ValidationMessageFor(model => model.ExpiryDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Issuer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IssuerID, new SelectList(ViewBag.Issuer, "IssuerID", "IssuerName"),@Model.Issuer ,new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Issuer)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LocationID, new SelectList(ViewBag.Location, "LocationID", "LocationName"),@Model.Location,new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Location)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssetType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AssetTypeID, new SelectList(ViewBag.AssetType, "AssetTypeID", "TypeDescription"), @Model.AssetType, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssetTypeID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssetStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AssetStatusID, new SelectList(ViewBag.AssetStatus, "AssetStatusID", "StatusDescription"),@Model.AssetStatus,new { @class = "form-control", @readonly=true, @disabled=true })
                @Html.ValidationMessageFor(model => model.AssetStatusID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssetClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AssetClassID, new SelectList(ViewBag.AssetClass, "AssetClassID", "ClassDescription","1" ),new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssetClassID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Remarks, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Remarks)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-3 pull-right">
                <input type="submit" value="SaveChanges" class="btn btn-primary" />
                @Html.ActionLink("Back", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#adate").datepicker({ dateFormat: 'mm/dd/yy' });
        $("#edate").datepicker({ dateFormat: 'mm/dd/yy' });
    });
</script>

FASTWeb/Views/FixAsset/Index.cshtml
@model IEnumerable<FASTWeb.Models.FixAsset.FixAssetViewModel>
@{
    ViewBag.Title = "Fix Asset List";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
    var list = new WebGrid(Model, canPage: true, rowsPerPage: 20, selectionFieldName: "selectedRow", ajaxUpdateContainerId: "listContainer");
    list.Pager(WebGridPagerModes.NextPrevious);
}

<br />
<div id="listContainer">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Fixed Asset List</h3>
        </div>
        <div class="panel-body" style="background-color:firebrick">
            <a class="btn btn-default pull-right" href="@Url.Action("NewAsset","FixAsset")">New Asset</a>
        </div>
        <div class="panel-body">
            @list.GetHtml(tableStyle: "table table-striped table-hover", headerStyle: "header", alternatingRowStyle: "alternateRow", selectedRowStyle: "select",
        columns: list.Columns(
                 list.Column("FixAssetID", "Asset ID", canSort: true, style: "col-lg-1"),
                 list.Column("AssetTag", "Asset Tag", canSort: true, style: "col-lg-1"),
                 list.Column("SerialNumber", "Serial Number", canSort: false, style: "col-lg-2"),
                 list.Column("AssetType", "Type", canSort: true, style: "col-lg-1"),
                 list.Column("Brand", "Brand", canSort: true, style: "col-lg-1"),
                 list.Column("Model", "Model", canSort: false, style: "col-lg-1"),
                 list.Column("AcquisitionDate", "Acquisition Date", canSort: false, style: "col-lg-2"),
                 list.Column("AssetClass", "Class", canSort: true, style: "col-lg-1"),
                          list.Column("AssetStatus", "Status", canSort: true, style: "col-lg-1"),         
                 list.Column(format: (item) => Html.ActionLink("Edit", "EditAsset", new { mod = item.FixAssetID }), style: "column-action")
                ))
        </div>
    </div>
</div>

FASTWeb/Views/FixAsset/NewAsset.cshtml
@model FASTWeb.Models.FixAsset.FixAssetViewModel

@{
    ViewBag.Title = "New Fix Asset";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>New Fix Asset</h2>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@using (Html.BeginForm("SaveNewAsset", "FixAsset", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.SerialNumber, htmlAttributes: new { @class = "control-label col-md-2 required" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SerialNumber, new { @class = "form-control", @autofocus="autofocus" })
                @Html.ValidationMessageFor(model => model.SerialNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssetTag, htmlAttributes: new { @class = "control-label col-md-2 required" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AssetTag, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssetTag)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2 required" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Brand, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Brand)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2 " })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Remarks, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Remarks)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AcquisitionDate, htmlAttributes: new { @class = "control-label col-md-2 required" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AcquisitionDate, new { @class="form-control", @id="adate"})
                @Html.ValidationMessageFor(model => model.AcquisitionDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ExpiryDate, new { @class = "form-control", @id = "edate" })
                @Html.ValidationMessageFor(model => model.ExpiryDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Issuer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IssuerID, new SelectList(ViewBag.Issuer, "IssuerID", "IssuerName"), "Choose one", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Issuer)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LocationID, new SelectList(ViewBag.Location, "LocationID", "LocationName"), "Choose one", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Location)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssetType, htmlAttributes: new { @class = "control-label col-md-2 required" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AssetTypeID, new SelectList(ViewBag.AssetType, "AssetTypeID", "TypeDescription"), "Choose one", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssetTypeID)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AssetClass, htmlAttributes: new { @class = "control-label col-md-2 required" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AssetClassID, new SelectList(ViewBag.AssetClass, "AssetClassID", "ClassDescription"), "Choose one", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssetClassID)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-default" })
            </div>
        </div>
        <div class="form-group" style="visibility:hidden">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model)
                @Html.ValidationMessageFor(model => model.Model)
            </div>
        </div>
        <div class="form-group" style="visibility:hidden">
            @Html.LabelFor(model => model.AssetStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AssetStatusID, new { @class = "form-control", disabled = false })
                @Html.ValidationMessageFor(model => model.AssetStatusID)
            </div>
        </div>

    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#adate").datepicker({ dateFormat: 'mm/dd/yy' });
        $("#edate").datepicker({ dateFormat: 'mm/dd/yy' });
    });
</script>