FASTWeb/Controllers/AuditTrailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FASTWeb.Controllers
{
    public class AuditTrailController : Controller
    {
        //
        // GET: /AuditTrail/
        [Authorize]
        public ActionResult Index()
        {
            FASTService.Process.AuditTrailProcess trailProcess = new FASTService.Process.AuditTrailProcess();
            List<FASTService.AuditTrail> trails = trailProcess.GetAuditTrails();
            return View(trails);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Search(string startDate, string employeeID, string assetTag, string assignmentID)
        {
            TempData["StartDate"] = startDate;
            TempData["EmployeeID"] = employeeID;
            TempData["AssetTag"] = assetTag;
            TempData["AssignmentID"] = assignmentID;

            FASTService.Process.AuditTrailProcess trailProcess = new FASTService.Process.AuditTrailProcess();
            List<FASTService.AuditTrail> trails = trailProcess.SearchAuditTrail(startDate, employeeID, assetTag, assignmentID);


            if (Request["Search"] != null)
            {
                
                return View("Index", trails);
            }
            else
            {
                return View("AuditReport", trails);
            }


            
        }
    }

       
}

FASTWeb/Views/AuditTrail/AuditReport.cshtml
@model IEnumerable<FASTService.AuditTrail>
@{
    Layout = null;
    //var searchKey = TempData["SearchKey"];
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    <title>Audit Report</title>
</head>
<body>
    <div class="container">
        <h1>FASTrack Online Reports</h1>
        <h3>Audit Report</h3>
        <table class="table table-bordered table-striped">
            <thead >
                <tr>
                    <th style="text-align:center;width:100px">Date</th>
                    <th style="text-align: center;width:90px">Employee ID</th>
                    <th style="text-align: center;width:90px">Assignment ID</th>
                    <th style="text-align: center;width:60px">Asset Tag</th>
                    <th style="text-align: center">Action</th>
                    <th style="text-align: center">Remarks</th>
                </tr>
            </thead>
            @if (Model != null && Model.Count() > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td style="text-align: center" >@Html.DisplayFor(modelItem => item.Date)</td>
                        <td style="text-align: center">@Html.DisplayFor(modelItem => item.EmployeeID)</td>
                        <td style="text-align: center" >@Html.DisplayFor(modelItem => item.AssignmentID)</td>
                        <td style="text-align: center">@Html.DisplayFor(modelItem => item.AssetTag)</td>
                        <td>@Html.DisplayFor(modelItem => item.Action)</td>
                        <td>@Html.DisplayFor(modelItem => item.AdditionalInformation)</td>
                    </tr>
                }
            }

        </table>
    </div>
</body>
</html>

FASTWeb/Views/AuditTrail/Index.cshtml
@model IEnumerable<FASTService.AuditTrail>
@{
    ViewBag.Title = "FASTrack Audit Trails";
   
    var trails = new WebGrid(Model, canPage: true, rowsPerPage: 25, selectionFieldName: "selectedRow", ajaxUpdateContainerId: "trailsContainer");
    trails.Pager(WebGridPagerModes.NextPrevious);

    var startDate = TempData["StartDate"];
    var employeeID = TempData["EmployeeID"];
    var assetTag = TempData["AssetTag"];
    var assignmentID = TempData["AssignmentID"];
}
<br/>
<div class="container-fluid">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h1 class="panel-title">Audit Trails</h1>
        </div>
        <div id="searchContainer" class="panel-body" style="background-color:aliceblue;">
                @using (Html.BeginForm("Search", "AuditTrail", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <form class="form-horizontal">
                        <fieldset>
                            <div class="form-group">
                                <label class="col-lg-2 control-label" for="startDate">Start Date</label>
                                <div class="col-lg-10">
                                    <input value="@startDate" style="width:160px" class="form-control" type="text" id="startDate" name="startDate" placeholder="Please select a date" maxlength="6" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 control-label" for="employeeID">Employee ID</label>
                                <div class="col-lg-3" style="width:150px">
                                    <input value="@employeeID" class="form-control" type="text" id="employeeID" name="employeeID" placeholder="Employee ID" maxlength="10" />
                                </div>
                                <label class="col-lg-2 control-label" for="assetTag">Asset Tag</label>
                                <div class="col-lg-3" style="width:150px">
                                    <input value="@assetTag" class="form-control" type="text" id="assetTag" name="assetTag" placeholder="Asset Tag" maxlength="50" />
                                </div>
                                <label class="col-lg-2 control-label" for="assignmentID">Assignment ID</label>
                                <div class="col-lg-3" style="width:150px">
                                    <input value="@assignmentID" class="form-control" type="text" id="ssignmentID" name="assignmentID" placeholder="Assignment ID" maxlength="6" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-10 col-lg-offset-2">
                                    <button type="submit" name="search" class="btn btn-primary">Search</button>
                                    <button type="submit" name="print" class="btn btn-default" formtarget="_blank">Print Result</button>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                }
            </div>
       
        <div id="trailsContainer" class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"></h3>
                </div>
                <div class="panel-body">
                    @trails.GetHtml(tableStyle: "table table-striped table-hover", headerStyle: "header", alternatingRowStyle: "alternateRow", selectedRowStyle: "select",
        columns: trails.Columns(
        trails.Column("Date", "Date", canSort: false, style: "col-lg-2"),
                 trails.Column("EmployeeID", "Employee ID", canSort: false, style: "col-lg-2 col-lg-offset-1"),
                 trails.Column("AssignmentID", "Assignment ID", canSort: false, style: "col-lg-2"),
                 trails.Column("AssetTag", "Asset Tag", canSort: false, style: "col-lg-1"),
                 trails.Column("Action", "Action", canSort: false, style: "col-lg-1"),
                 trails.Column("AdditionalInformation", "Remarks", canSort: false)
                ))
                </div>
            </div>
        
    </div>
    
            
    

          
</div>

<script type="text/javascript">
        $(document).ready(function () {
            $("#startDate").datepicker({ dateFormat: 'mm/dd/yy' });
        });
</script>